# Generated by Django 4.2.6 on 2023-11-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Waiting', max_length=30),
        ),
    ]
