# Generated by Django 4.2.6 on 2023-11-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_judge_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.filemodel'),
        ),
    ]
